"""add_revision_notes

Revision ID: 32db6b454627
Revises: 402f5f88d874
Create Date: 2026-05-29 16:48:08.977860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32db6b454627'
down_revision: Union[str, Sequence[str], None] = '402f5f88d874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_packages', sa.Column('revision_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_packages', 'revision_notes')
    # ### end Alembic commands ###
